// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqot51ycfUud7EIbExl3WkSyy72mI-Nn0',
    appId: '1:217887410294:web:b334b6e7e3a88a8d4f3757',
    messagingSenderId: '217887410294',
    projectId: 'wehealth-73e0d',
    authDomain: 'wehealth-73e0d.firebaseapp.com',
    storageBucket: 'wehealth-73e0d.firebasestorage.app',
    measurementId: 'G-TTCQV59KSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdoqjlGYFQNiUi3QB0VjmhAUxOctZY4lc',
    appId: '1:217887410294:android:d985d95de8fb7d054f3757',
    messagingSenderId: '217887410294',
    projectId: 'wehealth-73e0d',
    storageBucket: 'wehealth-73e0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOdhckJC_s3lJn0s975IBXwj6nAL9O6fM',
    appId: '1:217887410294:ios:751baec4a055eb664f3757',
    messagingSenderId: '217887410294',
    projectId: 'wehealth-73e0d',
    storageBucket: 'wehealth-73e0d.firebasestorage.app',
    iosBundleId: 'com.example.wehealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOdhckJC_s3lJn0s975IBXwj6nAL9O6fM',
    appId: '1:217887410294:ios:751baec4a055eb664f3757',
    messagingSenderId: '217887410294',
    projectId: 'wehealth-73e0d',
    storageBucket: 'wehealth-73e0d.firebasestorage.app',
    iosBundleId: 'com.example.wehealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqot51ycfUud7EIbExl3WkSyy72mI-Nn0',
    appId: '1:217887410294:web:7a0d9cef55a25e0b4f3757',
    messagingSenderId: '217887410294',
    projectId: 'wehealth-73e0d',
    authDomain: 'wehealth-73e0d.firebaseapp.com',
    storageBucket: 'wehealth-73e0d.firebasestorage.app',
    measurementId: 'G-CWYKLEDE1E',
  );
}
